"""Public Python client helpers for Lab Tracker consumers.

Key Lab Tracker idioms include first-line note markers for idempotent notes,
EntityRef note targets, project ids loaded from lt_ids.json, content-hash
evidence imports, and fail-soft figure capture with savefig/capture_figures.
"""

from lab_tracker_client.client import (
    ENTITY_TYPE_VALUES,
    EVIDENCE_METADATA_KEYS,
    NOTE_STATUS_VALUES,
    PROJECT_STATUS_VALUES,
    QUESTION_STATUS_VALUES,
    QUESTION_TYPE_VALUES,
    EntityRef,
    EvidenceImportResult,
    LabTracker,
    LTAPIError,
    LTError,
    LTRecord,
    LTValidationError,
    build_evidence_metadata,
    client,
    client_from_env,
    evidence_note_matches,
    file_sha256,
    find_evidence_note,
    find_note_by_marker,
    find_project_by_name,
    find_question_by_text,
    first_line_marker,
    health,
    ids,
    import_evidence_file,
    list_analyses,
    list_claims,
    list_datasets,
    list_goals,
    list_notes,
    list_projects,
    list_questions,
    list_sessions,
    list_visualizations,
    next_questions,
    quick_capture,
    readiness,
    upload_note_file,
    upsert_note,
    upsert_project,
    upsert_question,
)
from lab_tracker_client.figure import (
    FigureCaptureResult,
    RunContext,
    capture_figures,
    run_context,
    savefig,
)

__all__ = [
    "ENTITY_TYPE_VALUES",
    "EVIDENCE_METADATA_KEYS",
    "NOTE_STATUS_VALUES",
    "PROJECT_STATUS_VALUES",
    "QUESTION_STATUS_VALUES",
    "QUESTION_TYPE_VALUES",
    "EvidenceImportResult",
    "EntityRef",
    "FigureCaptureResult",
    "LTAPIError",
    "LTError",
    "LTRecord",
    "LTValidationError",
    "LabTracker",
    "RunContext",
    "build_evidence_metadata",
    "capture_figures",
    "client",
    "client_from_env",
    "evidence_note_matches",
    "file_sha256",
    "find_evidence_note",
    "find_note_by_marker",
    "find_project_by_name",
    "find_question_by_text",
    "first_line_marker",
    "health",
    "ids",
    "import_evidence_file",
    "list_analyses",
    "list_claims",
    "list_datasets",
    "list_goals",
    "list_notes",
    "list_projects",
    "list_questions",
    "list_sessions",
    "list_visualizations",
    "next_questions",
    "quick_capture",
    "readiness",
    "run_context",
    "savefig",
    "upload_note_file",
    "upsert_note",
    "upsert_project",
    "upsert_question",
]
