# Generated by Django 4.2.26 on 2025-11-27 03:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "eln_url",
                    models.URLField(
                        blank=True, help_text="Deep link to the canonical ELN page"
                    ),
                ),
                (
                    "eln_snapshot_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to ELN export snapshot",
                        max_length=500,
                    ),
                ),
                (
                    "eln_snapshot_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash of ELN snapshot for integrity verification",
                        max_length=128,
                    ),
                ),
                (
                    "eln_snapshot_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when ELN snapshot was taken",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "recipe_identifier",
                    models.CharField(
                        help_text="Identifier for the analysis recipe/pipeline",
                        max_length=200,
                    ),
                ),
                (
                    "recipe_version",
                    models.CharField(
                        blank=True, help_text="Version of the recipe", max_length=50
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Analysis parameters and configuration",
                    ),
                ),
                (
                    "job_identifier",
                    models.CharField(
                        blank=True,
                        help_text="Cluster job ID or execution identifier",
                        max_length=200,
                    ),
                ),
                (
                    "job_dashboard_url",
                    models.URLField(
                        blank=True, help_text="URL to job monitoring dashboard"
                    ),
                ),
                (
                    "output_path",
                    models.CharField(
                        blank=True, help_text="Path to analysis outputs", max_length=500
                    ),
                ),
                (
                    "outputs_manifest",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Manifest of output files and their locations",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scratch", "Scratch"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("reviewed", "Reviewed"),
                            ("frozen", "Frozen"),
                            ("published", "Published"),
                            ("failed", "Failed"),
                        ],
                        default="scratch",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("frozen_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Analyses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Claim",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "eln_url",
                    models.URLField(
                        blank=True, help_text="Deep link to the canonical ELN page"
                    ),
                ),
                (
                    "eln_snapshot_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to ELN export snapshot",
                        max_length=500,
                    ),
                ),
                (
                    "eln_snapshot_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash of ELN snapshot for integrity verification",
                        max_length=128,
                    ),
                ),
                (
                    "eln_snapshot_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when ELN snapshot was taken",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "statement",
                    models.TextField(help_text="The explicit scientific statement"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sketched", "Sketched"),
                            ("developing", "Developing"),
                            ("evidence_gathering", "Evidence Gathering"),
                            ("under_review", "Under Review"),
                            ("assessed", "Assessed"),
                            ("published", "Published"),
                            ("retracted", "Retracted"),
                        ],
                        default="sketched",
                        max_length=20,
                    ),
                ),
                (
                    "assessment_notes",
                    models.TextField(
                        blank=True, help_text="Notes from evidence assessment"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="core.claim",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Cohort",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "cohort_type",
                    models.CharField(
                        choices=[("pooled", "Pooled"), ("enumerated", "Enumerated")],
                        default="pooled",
                        max_length=20,
                    ),
                ),
                (
                    "genotype",
                    models.CharField(
                        blank=True,
                        help_text="Genetic background or transgenic line",
                        max_length=200,
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("mixed", "Mixed"),
                            ("unknown", "Unknown"),
                        ],
                        default="mixed",
                        max_length=10,
                    ),
                ),
                (
                    "rearing_conditions",
                    models.TextField(
                        blank=True,
                        help_text="Housing, diet, light cycle, and other rearing details",
                    ),
                ),
                (
                    "min_age_days",
                    models.PositiveIntegerField(
                        blank=True, help_text="Minimum age in days", null=True
                    ),
                ),
                (
                    "max_age_days",
                    models.PositiveIntegerField(
                        blank=True, help_text="Maximum age in days", null=True
                    ),
                ),
                (
                    "total_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of specimens in cohort"
                    ),
                ),
                (
                    "available_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of specimens currently available"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Dataset",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "eln_url",
                    models.URLField(
                        blank=True, help_text="Deep link to the canonical ELN page"
                    ),
                ),
                (
                    "eln_snapshot_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to ELN export snapshot",
                        max_length=500,
                    ),
                ),
                (
                    "eln_snapshot_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash of ELN snapshot for integrity verification",
                        max_length=128,
                    ),
                ),
                (
                    "eln_snapshot_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when ELN snapshot was taken",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "version",
                    models.CharField(
                        default="1.0",
                        help_text="Version identifier for the dataset",
                        max_length=50,
                    ),
                ),
                (
                    "inclusion_criteria",
                    models.TextField(
                        blank=True,
                        help_text="Criteria for including data in this dataset",
                    ),
                ),
                (
                    "replicate_targets",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Target replicate counts per condition cell",
                    ),
                ),
                (
                    "output_path",
                    models.CharField(
                        blank=True,
                        help_text="Canonical path to dataset outputs",
                        max_length=500,
                    ),
                ),
                (
                    "analysis_job_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of job identifiers for analysis processing",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("building", "Building"),
                            ("qc_pending", "QC Pending"),
                            ("frozen", "Frozen"),
                            ("published", "Published"),
                            ("deprecated", "Deprecated"),
                        ],
                        default="building",
                        max_length=20,
                    ),
                ),
                (
                    "frozen_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when dataset was frozen",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "eln_url",
                    models.URLField(
                        blank=True, help_text="Deep link to the canonical ELN page"
                    ),
                ),
                (
                    "eln_snapshot_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to ELN export snapshot",
                        max_length=500,
                    ),
                ),
                (
                    "eln_snapshot_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash of ELN snapshot for integrity verification",
                        max_length=128,
                    ),
                ),
                (
                    "eln_snapshot_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when ELN snapshot was taken",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "hypothesis",
                    models.TextField(
                        blank=True, help_text="The hypothesis to be tested"
                    ),
                ),
                (
                    "success_criteria",
                    models.TextField(
                        blank=True,
                        help_text="Criteria for evaluating whether the question is answered",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pilot", "Pilot"),
                            ("operational", "Operational"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "is_pilot",
                    models.BooleanField(
                        default=False,
                        help_text="True if this is an exploratory/pilot question",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="core.question",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Run",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "eln_url",
                    models.URLField(
                        blank=True, help_text="Deep link to the canonical ELN page"
                    ),
                ),
                (
                    "eln_snapshot_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to ELN export snapshot",
                        max_length=500,
                    ),
                ),
                (
                    "eln_snapshot_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash of ELN snapshot for integrity verification",
                        max_length=128,
                    ),
                ),
                (
                    "eln_snapshot_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when ELN snapshot was taken",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "data_sink",
                    models.CharField(
                        blank=True,
                        help_text="Path or identifier for where data will be stored",
                        max_length=500,
                    ),
                ),
                (
                    "planned_start",
                    models.DateTimeField(
                        blank=True, help_text="Planned start date/time", null=True
                    ),
                ),
                (
                    "planned_end",
                    models.DateTimeField(
                        blank=True, help_text="Planned end date/time", null=True
                    ),
                ),
                (
                    "success_criteria",
                    models.TextField(blank=True, help_text="Criteria for run success"),
                ),
                ("actual_start", models.DateTimeField(blank=True, null=True)),
                ("actual_end", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("scheduled", "Scheduled"),
                            ("running", "Running"),
                            ("qc", "Quality Control"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("archived", "Archived"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "cohort",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cohort for subject sourcing",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs",
                        to="core.cohort",
                    ),
                ),
                (
                    "questions",
                    models.ManyToManyField(
                        help_text="Questions this run addresses",
                        related_name="runs",
                        to="core.question",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Visualization",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "eln_url",
                    models.URLField(
                        blank=True, help_text="Deep link to the canonical ELN page"
                    ),
                ),
                (
                    "eln_snapshot_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to ELN export snapshot",
                        max_length=500,
                    ),
                ),
                (
                    "eln_snapshot_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash of ELN snapshot for integrity verification",
                        max_length=128,
                    ),
                ),
                (
                    "eln_snapshot_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when ELN snapshot was taken",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "asset_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to the visualization file",
                        max_length=500,
                    ),
                ),
                (
                    "asset_url",
                    models.URLField(
                        blank=True, help_text="URL if visualization is hosted"
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of asset: plot, video, interactive, etc.",
                        max_length=50,
                    ),
                ),
                (
                    "rendering_notebook",
                    models.CharField(
                        blank=True,
                        help_text="Path to notebook that generates this visualization",
                        max_length=500,
                    ),
                ),
                (
                    "rendering_script",
                    models.CharField(
                        blank=True,
                        help_text="Path to script that generates this visualization",
                        max_length=500,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags for discovery and filtering",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("reviewed", "Reviewed"),
                            ("frozen", "Frozen"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("frozen_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        blank=True,
                        help_text="Analysis that produced this visualization",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visualizations",
                        to="core.analysis",
                    ),
                ),
                (
                    "datasets",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Datasets referenced by this visualization",
                        related_name="visualizations",
                        to="core.dataset",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("scheduled_start", models.DateTimeField(blank=True, null=True)),
                ("scheduled_end", models.DateTimeField(blank=True, null=True)),
                ("actual_start", models.DateTimeField(blank=True, null=True)),
                ("actual_end", models.DateTimeField(blank=True, null=True)),
                (
                    "relative_offset_minutes",
                    models.IntegerField(
                        blank=True,
                        help_text="Offset in minutes from the referenced session",
                        null=True,
                    ),
                ),
                (
                    "rig_identifier",
                    models.CharField(
                        blank=True,
                        help_text="Identifier for the rig, room, or equipment",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "relative_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Another session this one is scheduled relative to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dependent_sessions",
                        to="core.session",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="core.run",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_start", "name"],
            },
        ),
        migrations.CreateModel(
            name="Panel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "eln_url",
                    models.URLField(
                        blank=True, help_text="Deep link to the canonical ELN page"
                    ),
                ),
                (
                    "eln_snapshot_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to ELN export snapshot",
                        max_length=500,
                    ),
                ),
                (
                    "eln_snapshot_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash of ELN snapshot for integrity verification",
                        max_length=128,
                    ),
                ),
                (
                    "eln_snapshot_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when ELN snapshot was taken",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Panel label, e.g., 'A', '2A', 'S1A'", max_length=50
                    ),
                ),
                (
                    "caption",
                    models.TextField(blank=True, help_text="Panel caption text"),
                ),
                (
                    "figure_identifier",
                    models.CharField(
                        blank=True,
                        help_text="Figure number or identifier, e.g., 'Figure 2', 'Figure S1'",
                        max_length=50,
                    ),
                ),
                (
                    "figure_role",
                    models.CharField(
                        choices=[
                            ("main", "Main Figure"),
                            ("supplement", "Supplementary Figure"),
                            ("extended", "Extended Data"),
                        ],
                        default="main",
                        max_length=20,
                    ),
                ),
                (
                    "frozen_file_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to frozen panel file",
                        max_length=500,
                    ),
                ),
                (
                    "frozen_file_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash of frozen file for integrity verification",
                        max_length=128,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("reviewed", "Reviewed"),
                            ("frozen", "Frozen"),
                            ("published", "Published"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("frozen_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "datasets",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Datasets underlying this panel",
                        related_name="panels",
                        to="core.dataset",
                    ),
                ),
                (
                    "visualization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Visualization this panel wraps",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="panels",
                        to="core.visualization",
                    ),
                ),
            ],
            options={
                "ordering": ["figure_identifier", "label"],
            },
        ),
        migrations.AddField(
            model_name="dataset",
            name="contributing_runs",
            field=models.ManyToManyField(
                blank=True,
                help_text="Additional runs contributing data",
                related_name="contributing_datasets",
                to="core.run",
            ),
        ),
        migrations.AddField(
            model_name="dataset",
            name="primary_run",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary run this dataset is associated with",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_datasets",
                to="core.run",
            ),
        ),
        migrations.AddField(
            model_name="dataset",
            name="sessions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific sessions included in dataset",
                related_name="datasets",
                to="core.session",
            ),
        ),
        migrations.CreateModel(
            name="Component",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("subjects", "Subjects"),
                            ("intervention", "Intervention"),
                            ("recording", "Recording"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "modality",
                    models.CharField(
                        blank=True,
                        help_text="E.g., 2-photon, ephys, behavior_video, optogenetics",
                        max_length=100,
                    ),
                ),
                (
                    "equipment_identifier",
                    models.CharField(
                        blank=True,
                        help_text="Identifier for specific equipment used",
                        max_length=200,
                    ),
                ),
                (
                    "start_offset_seconds",
                    models.IntegerField(
                        blank=True,
                        help_text="Start offset from session start in seconds",
                        null=True,
                    ),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(
                        blank=True, help_text="Expected duration in seconds", null=True
                    ),
                ),
                (
                    "requested_count",
                    models.PositiveIntegerField(
                        blank=True, help_text="Requested number of subjects", null=True
                    ),
                ),
                (
                    "consumed_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Actually consumed/used subjects",
                        null=True,
                    ),
                ),
                (
                    "sampling_notes",
                    models.TextField(
                        blank=True, help_text="Notes on subject selection and sampling"
                    ),
                ),
                (
                    "trial_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of trials for recording components",
                        null=True,
                    ),
                ),
                (
                    "trial_log_path",
                    models.CharField(
                        blank=True, help_text="Path to trial log file", max_length=500
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extensible metadata for role/modality-specific configuration",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("ready", "Ready"),
                            ("active", "Active"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "cohort",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cohort for subject components",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="components",
                        to="core.cohort",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="core.session",
                    ),
                ),
            ],
            options={
                "ordering": ["session", "role", "name"],
            },
        ),
        migrations.CreateModel(
            name="ClaimEvidence",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "evidence_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of evidence: supporting, refuting, contextual",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of how this evidence relates to the claim",
                    ),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claim_evidence_links",
                        to="core.analysis",
                    ),
                ),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_links",
                        to="core.claim",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claim_evidence_links",
                        to="core.dataset",
                    ),
                ),
                (
                    "panel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claim_evidence_links",
                        to="core.panel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Claim Evidence",
                "verbose_name_plural": "Claim Evidence",
            },
        ),
        migrations.AddField(
            model_name="claim",
            name="questions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Questions this claim is linked to",
                related_name="claims",
                to="core.question",
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="dataset",
            field=models.ForeignKey(
                blank=True,
                help_text="Dataset being analyzed",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="analyses",
                to="core.dataset",
            ),
        ),
    ]
