import json

from fastapi.testclient import TestClient

from lab_tracker.app import create_app


def test_frontend_routes_and_assets_are_served():
    client = TestClient(create_app())

    root_response = client.get("/", follow_redirects=False)
    assert root_response.status_code in (302, 307)
    assert root_response.headers["location"] == "/app/"

    bare_app_response = client.get("/app", follow_redirects=False)
    assert bare_app_response.status_code in (302, 307)
    assert bare_app_response.headers["location"] == "/app/"

    app_response = client.get("/app/")
    assert app_response.status_code == 200
    assert "text/html" in app_response.headers.get("content-type", "")
    assert "no-store" in app_response.headers["cache-control"]
    assert "no-cache" in app_response.headers["cache-control"]
    assert "<title>Lab Tracker</title>" in app_response.text
    assert 'id="app-root"' in app_response.text

    capture_response = client.get("/app/capture")
    assert capture_response.status_code == 200
    assert "no-store" in capture_response.headers["cache-control"]

    js_response = client.get("/app/static/app.js")
    assert js_response.status_code == 200
    assert "text/javascript" in js_response.headers.get("content-type", "")
    assert "generated by `npm run build:frontend`" in js_response.text
    assert "sourceMappingURL" not in js_response.text

    map_response = client.get("/app/static/app.js.map")
    assert map_response.status_code == 404

    assert "unpkg.com" not in app_response.text
    assert "text/babel" not in app_response.text
    assert app_response.headers["x-content-type-options"] == "nosniff"
    assert app_response.headers["x-frame-options"] == "DENY"
    assert app_response.headers["referrer-policy"] == "no-referrer"
    csp = app_response.headers["content-security-policy"]
    assert "default-src 'self'" in csp
    assert "object-src 'none'" in csp
    assert "frame-ancestors 'none'" in csp


def test_https_responses_include_hsts():
    client = TestClient(create_app(), base_url="https://lab.example.org")

    response = client.get("/app/")

    assert response.status_code == 200
    assert response.headers["strict-transport-security"].startswith("max-age=31536000")


def test_service_worker_is_served_with_app_scope():
    client = TestClient(create_app())

    response = client.get("/app/sw.js")
    assert response.status_code == 200
    assert "javascript" in response.headers["content-type"]
    assert "no-store" in response.headers["cache-control"]
    body = response.text
    assert "lab-tracker-shell-" in body
    assert "/app/static/app.js" in body
    assert "/app/static/manifest.json" in body
    assert "/app/share-target" in body
    # The route must beat the /app/{path} catch-all that serves index.html.
    assert "<!doctype html>" not in body.lower()


def test_share_target_post_falls_back_to_capture_redirect():
    client = TestClient(create_app())

    response = client.post(
        "/app/share-target",
        files={"file": ("snap.jpg", b"image-bytes", "image/jpeg")},
        follow_redirects=False,
    )
    assert response.status_code == 303
    assert response.headers["location"] == "/app/capture"


def test_manifest_declares_web_share_target():
    client = TestClient(create_app())

    manifest = client.get("/app/static/manifest.json").json()
    share_target = manifest["share_target"]
    assert share_target["action"] == "/app/share-target"
    assert share_target["method"] == "POST"
    assert share_target["enctype"] == "multipart/form-data"
    file_param = share_target["params"]["files"][0]
    assert file_param["name"] == "file"
    assert "image/*" in file_param["accept"]
    assert "audio/*" in file_param["accept"]


def test_pwa_manifest_and_icons_are_served():
    client = TestClient(create_app())

    app_response = client.get("/app/")
    assert '<link rel="manifest" href="/app/static/manifest.json" />' in app_response.text
    assert '<link rel="apple-touch-icon" href="/app/static/icon-180.png" />' in app_response.text
    assert '<meta name="theme-color" content="#0d8b6f" />' in app_response.text
    assert '<meta name="apple-mobile-web-app-capable" content="yes" />' in app_response.text

    manifest_response = client.get("/app/static/manifest.json")
    assert manifest_response.status_code == 200
    manifest = json.loads(manifest_response.content)
    assert manifest["name"] == "Lab Tracker"
    assert manifest["start_url"] == "/app/capture"
    assert manifest["display"] == "standalone"
    icon_srcs = {icon["src"] for icon in manifest["icons"]}
    assert "/app/static/icon-192.png" in icon_srcs
    assert "/app/static/icon-512.png" in icon_srcs

    for path in (
        "/app/static/icon-180.png",
        "/app/static/icon-192.png",
        "/app/static/icon-512.png",
    ):
        icon_response = client.get(path)
        assert icon_response.status_code == 200, path
        assert icon_response.headers["content-type"] == "image/png"
        assert icon_response.content.startswith(b"\x89PNG\r\n\x1a\n")
