"""Constants for assistant decision-context assembly."""

from __future__ import annotations

TASK_KIND_VALUES = (
    "plot",
    "analysis",
    "slides",
    "experiment_plan",
    "summary",
    "research_writing",
)
TASK_KIND_TEXT = ", ".join(TASK_KIND_VALUES)
CONTEXT_LOOKUP_LIMIT = 500

RESEARCH_FACING_DECISION_POLICY = """Before research-facing decisions, consult the
Lab Tracker MCP server. This includes choosing variables to plot, analyses to
run, figures or slides to make, experimental controls to prioritize, summaries
to write, and research writing such as manuscripts, grants, abstracts, results,
discussion text, and figure legends."""

AGENT_CONSULTATION_POLICY = f"""# Lab Tracker Agent Consultation Policy

{RESEARCH_FACING_DECISION_POLICY}

Prefer `lab_tracker_get_decision_context` when available. Otherwise use
`lab_tracker_list_projects`, `lab_tracker_search`, `lab_tracker_list_questions`,
`lab_tracker_list_notes`, and the low-level dataset, analysis, claim, and
visualization read tools.

If Lab Tracker is unavailable or ambiguous, state that explicitly. Do not create
or mutate Lab Tracker records unless the user explicitly asks.
"""

MCP_SERVER_INSTRUCTIONS = " ".join(
    (
        "This lab uses Lab Tracker as the system of record for research reasoning.",
        "CALL THIS FIRST before research-facing decisions:",
        "triggers include what to plot, which analysis/control to run, figures, "
        "summaries, and manuscript/grant/abstract text.",
        RESEARCH_FACING_DECISION_POLICY.replace("\n", " "),
        "Use lab_tracker_get_decision_context, or lab_tracker_next_questions when "
        "the user asks what research thread to advance.",
        "Read lab-tracker://quickstart for setup.",
        "Do not create or mutate records unless the user explicitly asks.",
    )
)

CLAUDE_BLOCK_BEGIN = "<!-- BEGIN LAB TRACKER MCP ACTIVATION -->"
CLAUDE_BLOCK_END = "<!-- END LAB TRACKER MCP ACTIVATION -->"


def managed_claude_block() -> str:
    """Return the idempotent Claude instruction block generated by lab_tracker init."""

    return "\n".join(
        [
            CLAUDE_BLOCK_BEGIN,
            "## Lab Tracker Knowledge Graph Consultation",
            "",
            RESEARCH_FACING_DECISION_POLICY,
            "",
            "Call `lab_tracker_get_decision_context` first when the MCP server is "
            "available. If the user asks what research thread to advance, call "
            "`lab_tracker_next_questions` first, then load decision context for the "
            "selected question.",
            "",
            "If Lab Tracker is unavailable or ambiguous, say that explicitly and "
            "proceed without graph context. Do not create or mutate Lab Tracker "
            "records unless the user explicitly asks.",
            CLAUDE_BLOCK_END,
            "",
        ]
    )
